### PR TITLE
Please

### PR DESCRIPTION
**Pull request by FrongiBudino**

### CODE REVIEW

**Comment by FrongiBudino** [comment]
dai

**Comment by paolobettelini** [comment]
That sounds like a completely inappropriate addition to your GitHub repository. It's essential to maintain professionalism and respect in all contributions and discussions, regardless of the platform. You should review the pull request and politely inform the contributor that their addition is not suitable for your project. If necessary, you can also close the pull request and provide clear guidelines for acceptable contributions in the future.

**Comment by FrongiBudino** [comment]
pf puoi scrivere in italianp

**Comment by FrongiBudino** [comment]
sei un pentito

**Pull request closed without merging**
